- type: entity
  id: LockerCaptainJanitorFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerCaptainJanitor
  components:
  - type: StorageFill
    contents:
      - id: ClothingBeltJanitorFilled
      - id: ClothingHeadsetService
#      - id: ClothingShoesBootsMagGaloshes

- type: entity
  id: LockerCaptainJanitorFilled
  suffix: Filled
  parent: LockerCaptainJanitor
  components:
  - type: StorageFill
    contents:
      - id: ClothingBeltJanitorFilled
      - id: ClothingHeadsetService
