- type: entity
  id: LockerCaptainJanitorFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerCaptainJanitor
  components:
  - type: StorageFill
    contents:
      - id: ClothingUniformJumpskirtJanitor
      - id: ClothingUniformJumpsuitJanitor
      - id: ClothingOuterWinterJani
      - id: ClothingUniformJumpskirtJanimaid
      - id: ClothingUniformJumpskirtJanimaidmini
      - id: ClothingBeltJanitorFilled
      - id: ClothingHeadsetService
      - id: ClothingHeadHatPurplesoft
      - id: ClothingHeadHatHoodBioJanitor
      - id: ClothingOuterBioJanitor
      - id: ClothingShoesBootsMagGaloshes
      - id: ClothingOuterHardsuitJanitor
      - id: NitrogenTankFilled
      - id: OxygenTankFilled
      - id: ClothingMaskBreath
      - id: JetpackMiniFilled
      - id: HandheldGPSBasic

- type: entity
  id: LockerCaptainJanitorFilled
  suffix: Filled
  parent: LockerCaptainJanitor
  components:
  - type: StorageFill
    contents:
      - id: ClothingUniformJumpskirtJanitor
      - id: ClothingUniformJumpsuitJanitor
      - id: ClothingOuterWinterJani
      - id: ClothingUniformJumpskirtJanimaid
      - id: ClothingUniformJumpskirtJanimaidmini
      - id: ClothingBeltJanitorFilled
      - id: ClothingHeadsetService
      - id: ClothingHeadHatPurplesoft
      - id: ClothingHeadHatHoodBioJanitor
      - id: ClothingOuterBioJanitor
      - id: ClothingShoesGaloshes
