- type: entity
  id: LockerCaptainJanitorFilled
  suffix: Filled
  parent: LockerJanitor
  components:
  - type: StorageFill
    contents:
      - id: ClothingBeltJanitorFilled
      - id: ClothingHeadsetService
