- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: DoctorGear
  equipment:
    shoes: ClothingShoesColorWhite
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
