#"Map":
#- 'Resources/Maps/**/*.yml' # All .yml files in the Resources/Maps directory, recursive.

"Map-Admin":
- 'Resources/Maps/_NF/Admin/*.yml' # Map Files

"Map-Bluespace":
- 'Resources/Maps/_NF/Bluespace/*.yml' # Map Files

"Map-Dungeon":
- 'Resources/Maps/_NF/Dungeon/*.yml' # Map Files

"Map-Outpost":
- 'Resources/Maps/_NF/Outpost/*.yml' # Map Files
- 'Resources/Prototypes/_MF/Maps/Outpost/*.yml' # Prototypes Files

"Map-Shuttle":
- 'Resources/Maps/_NF/Shuttles/*.yml' # All .yml files directly in the Resources/Maps/Shuttles directory.
- 'Resources/Prototypes/_NF/Shipyard/*.yml' # Shuttles!

"Map-POI":
- 'Resources/Maps/_NF/POI/*.yml' # All .yml files directly in the Resources/Maps/Shuttles directory.
- 'Resources/Prototypes/_MF/Maps/POI/*.yml' # Shuttles!