- type: entity
  parent: [BaseStructureLockImmuneToEmag, BaseStructureAccessReaderImmuneToEmag, BaseStructure]
  id: CrateTradeBaseSecure
  categories: [ HideSpawnMenu ]
  components:
  - type: Transform
    noRot: true
  - type: TradeCrate
  - type: Icon
    sprite: Structures/Storage/Crates/secure.rsi
    state: icon
  - type: Sprite
    noRot: true
    sprite: Structures/Storage/Crates/secure.rsi
    layers:
    - state: base
    - state: closed
    - state: paper
      sprite: Structures/Storage/Crates/labels.rsi
      map: ["enum.PaperLabelVisuals.Layer"]
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: StrongMetallic
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 100
      behaviors:
      - !type:DoActsBehavior
        acts: ["Destruction"]
  - type: Construction
    graph: CrateSecure
    node: cratesecure
  - type: Reflect
    reflects:
    - Energy
    reflectProb: 0.2
    spread: 90
  - type: StaticPrice
    price: 0
  - type: SentienceTarget
    flavorKind: station-event-random-sentience-flavor-inanimate
    weight: 0.01 # 100 trade crates = 1 animal
  - type: InteractionOutline
  - type: Physics
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.4,-0.4,0.4,0.29"
        density: 50
        mask:
        - CrateMask #this is so they can go under plastic flaps
        layer:
        - MachineLayer
  - type: Appearance
  - type: GenericVisualizer
    visuals:
      enum.PaperLabelVisuals.HasLabel:
        enum.PaperLabelVisuals.Layer:
          True: { visible: true }
          False: { visible: false }
      enum.PaperLabelVisuals.LabelType:
        enum.PaperLabelVisuals.Layer:
          Paper: { state: paper }
          Bounty: { state: bounty }
          CaptainsPaper: { state: captains_paper }
          Invoice: { state: invoice }
  - type: PaperLabel
    labelSlot:
      insertVerbText: Attach Label
      ejectVerbText: Remove Label
      whitelist:
        components:
        - Paper
      blacklist:
        tags:
        - Book
  - type: ContainerContainer
    containers:
      paper_label: !type:ContainerSlot
  - type: ItemSlots
  - type: RequireProjectileTarget
