# Base prototypes can be found in \Resources\Prototypes\Recipes\Lathes\security.yml

# Recipes

# Tracers: magazines

# .35 auto
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolTracer
  result: MagazinePistolTracer
  materials:
    Steel: 145
    Plastic: 50

# .20 rifle
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleTracer
  result: MagazineLightRifleTracer
  materials:
    Steel: 565
    Plastic: 135

# .30 rifle
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifleTracer
  result: MagazineRifleTracer
  materials:
    Steel: 475
    Plastic: 125

# .35 auto smg
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunTracer
  result: MagazinePistolSubMachineGunTracer
  materials:
    Steel: 300
    Plastic: 100

# Tracers: boxes

# .35 auto
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistolTracer
  result: MagazineBoxPistolTracer
  materials:
    Steel: 600
    Plastic: 200

# .30 rifle
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLightRifleTracer
  result: MagazineBoxLightRifleTracer
  materials:
    Steel: 750
    Plastic: 250

# .20 rifle
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxRifleTracer
  result: MagazineBoxRifleTracer
  materials:
    Steel: 900
    Plastic: 300
