- type: startingGear
  id: MobClippyGear
  equipment:
    head: ClothingHeadMailCarrier
#    ears: ClothingHeadsetService
    id: MailCarrierIDCard

- type: startingGear
  id: MobClarpyGear
  equipment:
    head: ClothingHeadHatPirate
    id: AgentIDCard

- type: startingGear
  id: MobCappyGear
  equipment:
    head: ClothingHeadHatNfsdSmallCampaign
    id: DeputyIDCard
