- type: entity
  id: CrateServiceJanitorialSupplies2
  parent: CratePlastic
  components:
  - type: StorageFill
    contents:
      - id: BoxTrashbag
        amount: 2
      - id: SprayBottleSpaceCleaner
        amount: 2
      - id: BoxWetFloorSign
