## Dynamic
# Shared between emagged protolathe and secfab
- type: latheRecipePack
  id: SecurityAmmoEmberfall
  recipes:
  - MagazinePistolTracer
  - MagazineLightRifleTracer
  - MagazinePistolSubMachineGunTracer
  - MagazineRifleTracer
  - MagazineBoxLightRifleTracer
  - MagazineBoxPistolTracer
  - MagazineBoxRifleTracer
