# POI's
Frontier: true
nfsd: true

anomalouslab:
  - WallPlastitaniumIndestructible
  - WallPlastitanium
  - PlastitaniumWindow
Cove:
  - WallPlastitanium
  - HighSecDoor
Lodge:
  - WallPlastitanium
  - HighSecDoor


# TECHNICAL DEBT BELOW. These ones were added to this list to ensure other PR's would not break upon merging. It is
# the intention for this list to become empty in separate PR's.
Bison:
  - WallPlastitanium
  - WallPlastitaniumDiagonal
Sprinter:
  - WallPlastitanium
  - IntercomSecurity
  - IntercomCommand
Courser:
  - HighSecDoor
Metastable:
  - SignSec
DartX:
  - HighSecDoor
Praeda:
  - ClothingEyesGlassesSecurity
  - EncryptionKeyCommand
  - EncryptionKeyEngineering
Pheonix:
  - DebugSubstation
  - WallPlastitanium
Spectre:
  - AirlockSecurity
  - EncryptionKeyMedicalScience
Anchor:
  - AirlockSecurity
  - IntercomCommand
DecadeDove:
  - EncryptionKeyCargo
  - EncryptionKeyEngineering
RosebudMKI:
  - EncryptionKeyCargo
  - EncryptionKeyEngineering
  - EncryptionKeyScience
  - EncryptionKeyService
Dragonfly:
  - EncryptionKeyCargo
  - EncryptionKeyEngineering
Opportunity:
  - EncryptionKeySecurity
RosebudMKII:
  - EncryptionKeyCargo
  - EncryptionKeyEngineering
  - EncryptionKeyScience
  - EncryptionKeyService
Pathfinder:
  - IntercomCommand
Schooner:
  - IntercomCommand
Marauder:
  - IntercomCommand
