- type: entity
  parent: SyndicateMicrowaveMachineCircuitboard
  id: AdvancedMicrowaveMachineCircuitBoard
  name: advanced microwave machine board
  components:
  - type: MachineBoard
    prototype: AdvancedMicrowave
